# Generated by Django 4.2.7 on 2023-11-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0002_categoryproduct_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproduct',
            name='created_at',
        ),
    ]
