# Generated by Django 4.2.7 on 2024-01-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publication_sign',
            field=models.BooleanField(default=False, verbose_name='признак публикации'),
        ),
    ]
