# Generated by Django 4.2.7 on 2023-11-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0003_remove_categoryproduct_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('inn', models.CharField(max_length=50, verbose_name='ИНН')),
                ('address', models.CharField(max_length=250, verbose_name='адресс')),
                ('support_email', models.EmailField(max_length=254, verbose_name='support email')),
            ],
            options={
                'verbose_name': 'кантакт',
                'verbose_name_plural': 'кантакты',
            },
        ),
    ]
