# Generated by Django 4.2.7 on 2023-12-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0004_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'контакт', 'verbose_name_plural': 'контакты'},
        ),
    ]
