# Generated by Django 4.2.7 on 2023-12-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryarticle',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.ImageField(default='default.png', upload_to='blog_img', verbose_name='превью'),
        ),
    ]
